(cl:defpackage rosdobot-srv
  (:use )
  (:export
   "SET_CP_CMD"
   "<SET_CP_CMD-REQUEST>"
   "SET_CP_CMD-REQUEST"
   "<SET_CP_CMD-RESPONSE>"
   "SET_CP_CMD-RESPONSE"
   "SETPARAMETERS"
   "<SETPARAMETERS-REQUEST>"
   "SETPARAMETERS-REQUEST"
   "<SETPARAMETERS-RESPONSE>"
   "SETPARAMETERS-RESPONSE"
   "SETPTPCMD"
   "<SETPTPCMD-REQUEST>"
   "SETPTPCMD-REQUEST"
   "<SETPTPCMD-RESPONSE>"
   "SETPTPCMD-RESPONSE"
  ))

