// Generated by gencpp from file rosdobot/set_cp_cmdResponse.msg
// DO NOT EDIT!


#ifndef ROSDOBOT_MESSAGE_SET_CP_CMDRESPONSE_H
#define ROSDOBOT_MESSAGE_SET_CP_CMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosdobot
{
template <class ContainerAllocator>
struct set_cp_cmdResponse_
{
  typedef set_cp_cmdResponse_<ContainerAllocator> Type;

  set_cp_cmdResponse_()
    : success(false)  {
    }
  set_cp_cmdResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct set_cp_cmdResponse_

typedef ::rosdobot::set_cp_cmdResponse_<std::allocator<void> > set_cp_cmdResponse;

typedef boost::shared_ptr< ::rosdobot::set_cp_cmdResponse > set_cp_cmdResponsePtr;
typedef boost::shared_ptr< ::rosdobot::set_cp_cmdResponse const> set_cp_cmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosdobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::rosdobot::set_cp_cmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosdobot/set_cp_cmdResponse";
  }

  static const char* value(const ::rosdobot::set_cp_cmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const ::rosdobot::set_cp_cmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct set_cp_cmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosdobot::set_cp_cmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosdobot::set_cp_cmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSDOBOT_MESSAGE_SET_CP_CMDRESPONSE_H
