// Generated by gencpp from file rosdobot/setParametersRequest.msg
// DO NOT EDIT!


#ifndef ROSDOBOT_MESSAGE_SETPARAMETERSREQUEST_H
#define ROSDOBOT_MESSAGE_SETPARAMETERSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rosdobot
{
template <class ContainerAllocator>
struct setParametersRequest_
{
  typedef setParametersRequest_<ContainerAllocator> Type;

  setParametersRequest_()
    : speed(0)
    , acceleration(0)  {
    }
  setParametersRequest_(const ContainerAllocator& _alloc)
    : speed(0)
    , acceleration(0)  {
  (void)_alloc;
    }



   typedef int64_t _speed_type;
  _speed_type speed;

   typedef int64_t _acceleration_type;
  _acceleration_type acceleration;




  typedef boost::shared_ptr< ::rosdobot::setParametersRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rosdobot::setParametersRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setParametersRequest_

typedef ::rosdobot::setParametersRequest_<std::allocator<void> > setParametersRequest;

typedef boost::shared_ptr< ::rosdobot::setParametersRequest > setParametersRequestPtr;
typedef boost::shared_ptr< ::rosdobot::setParametersRequest const> setParametersRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rosdobot::setParametersRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rosdobot::setParametersRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rosdobot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rosdobot::setParametersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rosdobot::setParametersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosdobot::setParametersRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rosdobot::setParametersRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosdobot::setParametersRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rosdobot::setParametersRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rosdobot::setParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0619ceca7f70341d044a39730c902c02";
  }

  static const char* value(const ::rosdobot::setParametersRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0619ceca7f70341dULL;
  static const uint64_t static_value2 = 0x044a39730c902c02ULL;
};

template<class ContainerAllocator>
struct DataType< ::rosdobot::setParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rosdobot/setParametersRequest";
  }

  static const char* value(const ::rosdobot::setParametersRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rosdobot::setParametersRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 speed\n\
int64 acceleration\n\
";
  }

  static const char* value(const ::rosdobot::setParametersRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rosdobot::setParametersRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setParametersRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rosdobot::setParametersRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rosdobot::setParametersRequest_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int64_t>::stream(s, indent + "  ", v.speed);
    s << indent << "acceleration: ";
    Printer<int64_t>::stream(s, indent + "  ", v.acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROSDOBOT_MESSAGE_SETPARAMETERSREQUEST_H
