// Generated by gencpp from file rosdobot/setParameters.msg
// DO NOT EDIT!


#ifndef ROSDOBOT_MESSAGE_SETPARAMETERS_H
#define ROSDOBOT_MESSAGE_SETPARAMETERS_H

#include <ros/service_traits.h>


#include <rosdobot/setParametersRequest.h>
#include <rosdobot/setParametersResponse.h>


namespace rosdobot
{

struct setParameters
{

typedef setParametersRequest Request;
typedef setParametersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setParameters
} // namespace rosdobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosdobot::setParameters > {
  static const char* value()
  {
    return "301ef563d5855468df19cad9318fe7e6";
  }

  static const char* value(const ::rosdobot::setParameters&) { return value(); }
};

template<>
struct DataType< ::rosdobot::setParameters > {
  static const char* value()
  {
    return "rosdobot/setParameters";
  }

  static const char* value(const ::rosdobot::setParameters&) { return value(); }
};


// service_traits::MD5Sum< ::rosdobot::setParametersRequest> should match 
// service_traits::MD5Sum< ::rosdobot::setParameters > 
template<>
struct MD5Sum< ::rosdobot::setParametersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosdobot::setParameters >::value();
  }
  static const char* value(const ::rosdobot::setParametersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosdobot::setParametersRequest> should match 
// service_traits::DataType< ::rosdobot::setParameters > 
template<>
struct DataType< ::rosdobot::setParametersRequest>
{
  static const char* value()
  {
    return DataType< ::rosdobot::setParameters >::value();
  }
  static const char* value(const ::rosdobot::setParametersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosdobot::setParametersResponse> should match 
// service_traits::MD5Sum< ::rosdobot::setParameters > 
template<>
struct MD5Sum< ::rosdobot::setParametersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosdobot::setParameters >::value();
  }
  static const char* value(const ::rosdobot::setParametersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosdobot::setParametersResponse> should match 
// service_traits::DataType< ::rosdobot::setParameters > 
template<>
struct DataType< ::rosdobot::setParametersResponse>
{
  static const char* value()
  {
    return DataType< ::rosdobot::setParameters >::value();
  }
  static const char* value(const ::rosdobot::setParametersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSDOBOT_MESSAGE_SETPARAMETERS_H
