// Generated by gencpp from file rosdobot/setPTPCMD.msg
// DO NOT EDIT!


#ifndef ROSDOBOT_MESSAGE_SETPTPCMD_H
#define ROSDOBOT_MESSAGE_SETPTPCMD_H

#include <ros/service_traits.h>


#include <rosdobot/setPTPCMDRequest.h>
#include <rosdobot/setPTPCMDResponse.h>


namespace rosdobot
{

struct setPTPCMD
{

typedef setPTPCMDRequest Request;
typedef setPTPCMDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setPTPCMD
} // namespace rosdobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosdobot::setPTPCMD > {
  static const char* value()
  {
    return "e79fccf745467b8a4a219f9c2bccd690";
  }

  static const char* value(const ::rosdobot::setPTPCMD&) { return value(); }
};

template<>
struct DataType< ::rosdobot::setPTPCMD > {
  static const char* value()
  {
    return "rosdobot/setPTPCMD";
  }

  static const char* value(const ::rosdobot::setPTPCMD&) { return value(); }
};


// service_traits::MD5Sum< ::rosdobot::setPTPCMDRequest> should match 
// service_traits::MD5Sum< ::rosdobot::setPTPCMD > 
template<>
struct MD5Sum< ::rosdobot::setPTPCMDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosdobot::setPTPCMD >::value();
  }
  static const char* value(const ::rosdobot::setPTPCMDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosdobot::setPTPCMDRequest> should match 
// service_traits::DataType< ::rosdobot::setPTPCMD > 
template<>
struct DataType< ::rosdobot::setPTPCMDRequest>
{
  static const char* value()
  {
    return DataType< ::rosdobot::setPTPCMD >::value();
  }
  static const char* value(const ::rosdobot::setPTPCMDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosdobot::setPTPCMDResponse> should match 
// service_traits::MD5Sum< ::rosdobot::setPTPCMD > 
template<>
struct MD5Sum< ::rosdobot::setPTPCMDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosdobot::setPTPCMD >::value();
  }
  static const char* value(const ::rosdobot::setPTPCMDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosdobot::setPTPCMDResponse> should match 
// service_traits::DataType< ::rosdobot::setPTPCMD > 
template<>
struct DataType< ::rosdobot::setPTPCMDResponse>
{
  static const char* value()
  {
    return DataType< ::rosdobot::setPTPCMD >::value();
  }
  static const char* value(const ::rosdobot::setPTPCMDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSDOBOT_MESSAGE_SETPTPCMD_H
